export const MENU_DATA = [
  // Breakfast Veg
  {id:1,name:"Plain Dosa",cat:"Breakfast",subcat:"Veg",price:40,type:"veg",available:true,popular:false,tags:["breakfast","light"],image:"assets/breakfast.png"},
  {id:2,name:"Karam Dosa",cat:"Breakfast",subcat:"Veg",price:40,type:"veg",available:true,popular:false,tags:["breakfast","spicy"],image:"assets/breakfast.png"},
  {id:3,name:"Onion Dosa",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:true,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:4,name:"Upma Dosa",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:5,name:"Chee Karam Dosa",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast","spicy"],image:"assets/breakfast.png"},
  {id:6,name:"Masala Dosa",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:true,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:7,name:"Cheese Masala Dosa",cat:"Breakfast",subcat:"Veg",price:60,type:"veg",available:true,popular:false,tags:["breakfast","cheese"],image:"assets/breakfast.png"},
  {id:8,name:"Butter Dosa",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:9,name:"Paneer Dosa",cat:"Breakfast",subcat:"Veg",price:80,type:"veg",available:true,popular:false,tags:["breakfast","paneer"],image:"assets/breakfast.png"},
  {id:10,name:"Egg Dosa",cat:"Breakfast",subcat:"NonVeg",price:50,type:"nonveg",available:true,popular:false,tags:["breakfast","egg"],image:"assets/egg_dishes.png"},
  {id:11,name:"Double Egg Dosa",cat:"Breakfast",subcat:"NonVeg",price:60,type:"nonveg",available:true,popular:false,tags:["breakfast","egg"],image:"assets/egg_dishes.png"},
  {id:12,name:"Carrot Dosa",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast","healthy"],image:"assets/breakfast.png"},
  {id:13,name:"Carrot Masala Dosa",cat:"Breakfast",subcat:"Veg",price:60,type:"veg",available:true,popular:false,tags:["breakfast","healthy"],image:"assets/breakfast.png"},
  {id:14,name:"Pessarattu",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:15,name:"Onion Pessarattu",cat:"Breakfast",subcat:"Veg",price:60,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:16,name:"Upma Pessarattu",cat:"Breakfast",subcat:"Veg",price:60,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:17,name:"Uthappam",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/breakfast.png"},
  {id:18,name:"Idly",cat:"Breakfast",subcat:"Veg",price:30,type:"veg",available:true,popular:true,tags:["breakfast","light"],image:"assets/idly_vada.png"},
  {id:19,name:"Chee Karam Idly",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast","spicy"],image:"assets/idly_vada.png"},
  {id:20,name:"Sambar Idly",cat:"Breakfast",subcat:"Veg",price:40,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/idly_vada.png"},
  {id:21,name:"Vada",cat:"Breakfast",subcat:"Veg",price:30,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/idly_vada.png"},
  {id:22,name:"2 Idly 1 Vada",cat:"Breakfast",subcat:"Veg",price:40,type:"veg",available:true,popular:true,tags:["breakfast","combo"],image:"assets/idly_vada.png"},
  {id:23,name:"Sambar Vada",cat:"Breakfast",subcat:"Veg",price:40,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/idly_vada.png"},
  {id:24,name:"Mysore Bonda",cat:"Breakfast",subcat:"Veg",price:40,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/idly_vada.png"},
  {id:25,name:"Puri",cat:"Breakfast",subcat:"Veg",price:50,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/paratha.png"},
  {id:26,name:"Chapati",cat:"Breakfast",subcat:"Veg",price:70,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/paratha.png"},
  {id:27,name:"Parrota",cat:"Breakfast",subcat:"Veg",price:70,type:"veg",available:true,popular:false,tags:["breakfast"],image:"assets/paratha.png"},
  // Breakfast NonVeg
  {id:28,name:"Egg Parota",cat:"Breakfast",subcat:"NonVeg",price:80,type:"nonveg",available:true,popular:false,tags:["breakfast","egg"],image:"assets/egg_dishes.png"},
  {id:29,name:"Egg Chapati",cat:"Breakfast",subcat:"NonVeg",price:80,type:"nonveg",available:true,popular:false,tags:["breakfast","egg"],image:"assets/egg_dishes.png"},
  {id:30,name:"Dosa with Chicken Curry",cat:"Breakfast",subcat:"NonVeg",price:99,type:"nonveg",available:true,popular:true,tags:["breakfast","chicken"],image:"assets/breakfast.png"},
  {id:31,name:"Puri with Chicken Curry",cat:"Breakfast",subcat:"NonVeg",price:99,type:"nonveg",available:true,popular:false,tags:["breakfast","chicken"],image:"assets/paratha.png"},
  {id:32,name:"Chapati with Chicken Curry",cat:"Breakfast",subcat:"NonVeg",price:119,type:"nonveg",available:true,popular:false,tags:["breakfast","chicken"],image:"assets/paratha.png"},
  {id:33,name:"Parota with Chicken Curry",cat:"Breakfast",subcat:"NonVeg",price:119,type:"nonveg",available:true,popular:false,tags:["breakfast","chicken"],image:"assets/paratha.png"},
  {id:34,name:"Omelette",cat:"Breakfast",subcat:"NonVeg",price:50,type:"nonveg",available:true,popular:false,tags:["breakfast","egg"],image:"assets/egg_dishes.png"},
  // Starters Veg
  {id:35,name:"Veg Manchurian",cat:"Starters",subcat:"Veg",price:90,type:"veg",available:true,popular:false,tags:["starter","chinese"],image:"assets/starters.png"},
  {id:36,name:"Gobi Manchurian",cat:"Starters",subcat:"Veg",price:100,type:"veg",available:true,popular:true,tags:["starter","chinese","spicy"],image:"assets/starters.png"},
  {id:37,name:"Gobi 65",cat:"Starters",subcat:"Veg",price:110,type:"veg",available:true,popular:false,tags:["starter","spicy"],image:"assets/starters.png"},
  {id:38,name:"Chilli Paneer",cat:"Starters",subcat:"Veg",price:159,type:"veg",available:true,popular:true,tags:["starter","paneer","spicy"],image:"assets/starters.png"},
  {id:39,name:"Paneer 65",cat:"Starters",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["starter","paneer"],image:"assets/starters.png"},
  {id:40,name:"Paneer Majestic",cat:"Starters",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["starter","paneer"],image:"assets/starters.png"},
  {id:41,name:"Dragon Paneer",cat:"Starters",subcat:"Veg",price:169,type:"veg",available:true,popular:false,tags:["starter","paneer","spicy"],image:"assets/starters.png"},
  {id:42,name:"Chilli Mushroom",cat:"Starters",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["starter","mushroom"],image:"assets/starters.png"},
  {id:43,name:"Mushroom Salt and Pepper",cat:"Starters",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["starter","mushroom"],image:"assets/starters.png"},
  {id:44,name:"Chilli Baby Corn",cat:"Starters",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["starter"],image:"assets/starters.png"},
  {id:45,name:"Baby Corn Manchurian",cat:"Starters",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["starter","chinese"],image:"assets/starters.png"},
  // Starters NonVeg
  {id:46,name:"Egg Manchurian",cat:"Starters",subcat:"NonVeg",price:99,type:"nonveg",available:true,popular:false,tags:["starter","egg"],image:"assets/egg_dishes.png"},
  {id:47,name:"Chilli Egg",cat:"Starters",subcat:"NonVeg",price:119,type:"nonveg",available:true,popular:false,tags:["starter","egg","spicy"],image:"assets/egg_dishes.png"},
  {id:48,name:"Egg 65",cat:"Starters",subcat:"NonVeg",price:129,type:"nonveg",available:true,popular:false,tags:["starter","egg"],image:"assets/egg_dishes.png"},
  {id:49,name:"Chicken Manchurian",cat:"Starters",subcat:"NonVeg",price:169,type:"nonveg",available:true,popular:false,tags:["starter","chicken","chinese"],image:"assets/chicken_starters.png"},
  {id:50,name:"Chicken 65",cat:"Starters",subcat:"NonVeg",price:169,type:"nonveg",available:true,popular:true,tags:["starter","chicken","spicy"],image:"assets/chicken_starters.png"},
  {id:51,name:"Chilli Chicken",cat:"Starters",subcat:"NonVeg",price:179,type:"nonveg",available:true,popular:true,tags:["starter","chicken","spicy"],image:"assets/chicken_starters.png"},
  {id:52,name:"Chicken Majestic",cat:"Starters",subcat:"NonVeg",price:189,type:"nonveg",available:true,popular:false,tags:["starter","chicken"],image:"assets/chicken_starters.png"},
  {id:53,name:"Chicken Lollipop",cat:"Starters",subcat:"NonVeg",price:219,type:"nonveg",available:true,popular:true,tags:["starter","chicken"],image:"assets/chicken_starters.png"},
  {id:54,name:"Chicken Drumstick",cat:"Starters",subcat:"NonVeg",price:219,type:"nonveg",available:true,popular:false,tags:["starter","chicken"],image:"assets/chicken_starters.png"},
  {id:55,name:"Chicken 555",cat:"Starters",subcat:"NonVeg",price:189,type:"nonveg",available:true,popular:false,tags:["starter","chicken"],image:"assets/chicken_starters.png"},
  {id:56,name:"Dragon Chicken",cat:"Starters",subcat:"NonVeg",price:189,type:"nonveg",available:true,popular:false,tags:["starter","chicken","spicy"],image:"assets/chicken_starters.png"},
  {id:57,name:"Chicken Pakodi",cat:"Starters",subcat:"NonVeg",price:159,type:"nonveg",available:true,popular:false,tags:["starter","chicken"],image:"assets/chicken_starters.png"},
  {id:58,name:"Zest SPL Pachi Mirchi Kodi Vepudu",cat:"Starters",subcat:"NonVeg",price:219,type:"nonveg",available:true,popular:false,tags:["starter","chicken","spicy","special"],image:"assets/chicken_starters.png"},
  // Seafood
  {id:59,name:"Loose Prawns (Dry)",cat:"Starters",subcat:"Seafood",price:219,type:"nonveg",available:true,popular:false,tags:["starter","prawns"],image:"assets/starters.png"},
  {id:60,name:"Chilli Prawns (Wet)",cat:"Starters",subcat:"Seafood",price:219,type:"nonveg",available:true,popular:false,tags:["starter","prawns","spicy"],image:"assets/starters.png"},
  {id:61,name:"Fried Fish (Dry)",cat:"Starters",subcat:"Seafood",price:219,type:"nonveg",available:true,popular:false,tags:["starter","fish"],image:"assets/starters.png"},
  {id:62,name:"Apollo Fish (Wet)",cat:"Starters",subcat:"Seafood",price:219,type:"nonveg",available:true,popular:false,tags:["starter","fish"],image:"assets/starters.png"},
  // Fried Rice
  {id:63,name:"Veg Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:90,type:"veg",available:true,popular:false,tags:["rice","chinese"],image:"assets/pulao.png"},
  {id:64,name:"Veg Schezwan Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:100,type:"veg",available:true,popular:false,tags:["rice","chinese","spicy"],image:"assets/pulao.png"},
  {id:65,name:"Gobi Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:110,type:"veg",available:true,popular:false,tags:["rice","chinese"],image:"assets/pulao.png"},
  {id:66,name:"Manchuria Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:100,type:"veg",available:true,popular:false,tags:["rice","chinese"],image:"assets/pulao.png"},
  {id:67,name:"Mushroom Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:120,type:"veg",available:true,popular:false,tags:["rice","chinese"],image:"assets/pulao.png"},
  {id:68,name:"Paneer Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:130,type:"veg",available:true,popular:false,tags:["rice","chinese","paneer"],image:"assets/pulao.png"},
  {id:69,name:"Kaju Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:130,type:"veg",available:true,popular:false,tags:["rice"],image:"assets/pulao.png"},
  {id:70,name:"Egg Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:100,type:"nonveg",available:true,popular:true,tags:["rice","chinese","egg"],image:"assets/pulao.png"},
  {id:71,name:"Schezwan Egg Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:110,type:"nonveg",available:true,popular:false,tags:["rice","chinese","egg","spicy"],image:"assets/pulao.png"},
  {id:72,name:"Chicken Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:130,type:"nonveg",available:true,popular:true,tags:["rice","chinese","chicken"],image:"assets/pulao.png"},
  {id:73,name:"Schezwan Chicken Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:140,type:"nonveg",available:true,popular:false,tags:["rice","chinese","chicken","spicy"],image:"assets/pulao.png"},
  {id:74,name:"Prawns Fried Rice",cat:"FastFood",subcat:"Fried Rice",price:170,type:"nonveg",available:true,popular:false,tags:["rice","prawns"],image:"assets/pulao.png"},
  // Noodles
  {id:75,name:"Veg Noodles",cat:"FastFood",subcat:"Noodles",price:90,type:"veg",available:true,popular:false,tags:["noodles","chinese"],image:"assets/noodles.png"},
  {id:76,name:"Schezwan Veg Noodles",cat:"FastFood",subcat:"Noodles",price:100,type:"veg",available:true,popular:false,tags:["noodles","chinese","spicy"],image:"assets/noodles.png"},
  {id:77,name:"Manchurian Noodles",cat:"FastFood",subcat:"Noodles",price:100,type:"veg",available:true,popular:false,tags:["noodles","chinese"],image:"assets/noodles.png"},
  {id:78,name:"Gobi Manchurian Noodles",cat:"FastFood",subcat:"Noodles",price:129,type:"veg",available:true,popular:false,tags:["noodles","chinese"],image:"assets/noodles.png"},
  {id:79,name:"Chilli Garlic Noodles",cat:"FastFood",subcat:"Noodles",price:119,type:"veg",available:true,popular:false,tags:["noodles","chinese","spicy"],image:"assets/noodles.png"},
  {id:80,name:"Egg Noodles",cat:"FastFood",subcat:"Noodles",price:110,type:"nonveg",available:true,popular:false,tags:["noodles","egg"],image:"assets/noodles.png"},
  {id:81,name:"Chicken Noodles",cat:"FastFood",subcat:"Noodles",price:130,type:"nonveg",available:true,popular:false,tags:["noodles","chicken"],image:"assets/noodles.png"},
  {id:82,name:"Schezwan Chicken Noodles",cat:"FastFood",subcat:"Noodles",price:140,type:"nonveg",available:true,popular:false,tags:["noodles","chicken","spicy"],image:"assets/noodles.png"},
  // Biryani Veg
  {id:83,name:"Veg DUM Biryani",cat:"MainCourse",subcat:"Biryani",price:149,type:"veg",available:true,popular:true,tags:["biryani","rice"],image:"assets/biryani.png"},
  {id:84,name:"Paneer Biryani",cat:"MainCourse",subcat:"Biryani",price:220,type:"veg",available:true,popular:false,tags:["biryani","rice","paneer"],image:"assets/biryani.png"},
  {id:85,name:"Mushroom Biryani",cat:"MainCourse",subcat:"Biryani",price:220,type:"veg",available:true,popular:false,tags:["biryani","rice","mushroom"],image:"assets/biryani.png"},
  {id:86,name:"Kaju Biryani",cat:"MainCourse",subcat:"Biryani",price:220,type:"veg",available:true,popular:false,tags:["biryani","rice"],image:"assets/biryani.png"},
  // Biryani NonVeg
  {id:87,name:"Chicken DUM Biryani (Single)",cat:"MainCourse",subcat:"Biryani",price:139,type:"nonveg",available:true,popular:true,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:88,name:"Chicken DUM Biryani (Full)",cat:"MainCourse",subcat:"Biryani",price:179,type:"nonveg",available:true,popular:true,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:89,name:"Chicken Rambo Biryani (2pcs)",cat:"MainCourse",subcat:"Biryani",price:259,type:"nonveg",available:true,popular:false,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:90,name:"Chicken Wings Biryani (3pcs)",cat:"MainCourse",subcat:"Biryani",price:259,type:"nonveg",available:true,popular:false,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:91,name:"Chicken Fry Piece Biryani",cat:"MainCourse",subcat:"Biryani",price:259,type:"nonveg",available:true,popular:false,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:92,name:"Chicken Boneless Biryani",cat:"MainCourse",subcat:"Biryani",price:269,type:"nonveg",available:true,popular:true,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:93,name:"Chicken Mughlai Biryani",cat:"MainCourse",subcat:"Biryani",price:269,type:"nonveg",available:true,popular:false,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:94,name:"Tandoori Chicken Biryani",cat:"MainCourse",subcat:"Biryani",price:299,type:"nonveg",available:true,popular:false,tags:["biryani","rice","chicken","tandoori"],image:"assets/biryani.png"},
  {id:95,name:"Tangdi Chicken Biryani",cat:"MainCourse",subcat:"Biryani",price:279,type:"nonveg",available:true,popular:false,tags:["biryani","rice","chicken"],image:"assets/biryani.png"},
  {id:96,name:"Prawns Biryani",cat:"MainCourse",subcat:"Biryani",price:289,type:"nonveg",available:true,popular:false,tags:["biryani","rice","prawns"],image:"assets/biryani.png"},
  {id:97,name:"Fish Biryani",cat:"MainCourse",subcat:"Biryani",price:289,type:"nonveg",available:true,popular:false,tags:["biryani","rice","fish"],image:"assets/biryani.png"},
  // Pulaos
  {id:98,name:"Veg Pulao",cat:"MainCourse",subcat:"Pulao",price:130,type:"veg",available:true,popular:false,tags:["pulao","rice"],image:"assets/pulao.png"},
  {id:99,name:"Paneer Pulao",cat:"MainCourse",subcat:"Pulao",price:169,type:"veg",available:true,popular:false,tags:["pulao","rice","paneer"],image:"assets/pulao.png"},
  {id:100,name:"Kaju Pulao",cat:"MainCourse",subcat:"Pulao",price:169,type:"veg",available:true,popular:false,tags:["pulao","rice"],image:"assets/pulao.png"},
  {id:101,name:"Chicken Pulao",cat:"MainCourse",subcat:"Pulao",price:179,type:"nonveg",available:true,popular:false,tags:["pulao","rice","chicken"],image:"assets/pulao.png"},
  {id:102,name:"Fry Piece Chicken Pulao",cat:"MainCourse",subcat:"Pulao",price:179,type:"nonveg",available:true,popular:false,tags:["pulao","rice","chicken"],image:"assets/pulao.png"},
  {id:103,name:"Prawns Pulao",cat:"MainCourse",subcat:"Pulao",price:229,type:"nonveg",available:true,popular:false,tags:["pulao","rice","prawns"],image:"assets/pulao.png"},
  {id:104,name:"Zest SPL Pachi Mirchi Kodi Pulao",cat:"MainCourse",subcat:"Pulao",price:189,type:"nonveg",available:true,popular:false,tags:["pulao","rice","chicken","special"],image:"assets/pulao.png"},
  // Rice Bowls
  {id:105,name:"Tomato Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:89,type:"veg",available:true,popular:false,tags:["rice","bowl","light"],image:"assets/pulao.png"},
  {id:106,name:"Aloo 65 Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:99,type:"veg",available:true,popular:false,tags:["rice","bowl"],image:"assets/pulao.png"},
  {id:107,name:"Paneer Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:129,type:"veg",available:true,popular:false,tags:["rice","bowl","paneer"],image:"assets/pulao.png"},
  {id:108,name:"Sambar Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:109,type:"veg",available:true,popular:false,tags:["rice","bowl"],image:"assets/pulao.png"},
  {id:109,name:"Curd Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:99,type:"veg",available:true,popular:false,tags:["rice","bowl","light"],image:"assets/pulao.png"},
  {id:110,name:"Veg Meals",cat:"MainCourse",subcat:"Rice Bowls",price:99,type:"veg",available:true,popular:true,tags:["meals","veg","budget"],image:"assets/meals.png"},
  {id:111,name:"Chicken Sambar Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:129,type:"nonveg",available:true,popular:false,tags:["rice","bowl","chicken"],image:"assets/pulao.png"},
  {id:112,name:"Chilli Chicken Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:149,type:"nonveg",available:true,popular:false,tags:["rice","bowl","chicken","spicy"],image:"assets/pulao.png"},
  {id:113,name:"Chicken 65 Rice Bowl",cat:"MainCourse",subcat:"Rice Bowls",price:149,type:"nonveg",available:true,popular:false,tags:["rice","bowl","chicken"],image:"assets/pulao.png"},
  // Veg Curries
  {id:114,name:"Mixed Veg Curry",cat:"Curries",subcat:"Veg",price:129,type:"veg",available:true,popular:false,tags:["curry","veg"],image:"assets/curry.png"},
  {id:115,name:"Paneer Butter Masala",cat:"Curries",subcat:"Veg",price:159,type:"veg",available:true,popular:true,tags:["curry","paneer"],image:"assets/curry.png"},
  {id:116,name:"Paneer Kadai",cat:"Curries",subcat:"Veg",price:169,type:"veg",available:true,popular:false,tags:["curry","paneer"],image:"assets/curry.png"},
  {id:117,name:"Paneer Shahi Kurma",cat:"Curries",subcat:"Veg",price:169,type:"veg",available:true,popular:false,tags:["curry","paneer"],image:"assets/curry.png"},
  {id:118,name:"Kaju Paneer Curry",cat:"Curries",subcat:"Veg",price:169,type:"veg",available:true,popular:false,tags:["curry","paneer"],image:"assets/curry.png"},
  {id:119,name:"Kaju Curry",cat:"Curries",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["curry"],image:"assets/curry.png"},
  {id:120,name:"Paneer Tikka Masala",cat:"Curries",subcat:"Veg",price:159,type:"veg",available:true,popular:false,tags:["curry","paneer","tikka"],image:"assets/curry.png"},
  {id:121,name:"Paneer Methi",cat:"Curries",subcat:"Veg",price:149,type:"veg",available:true,popular:false,tags:["curry","paneer"],image:"assets/curry.png"},
  // NonVeg Curries
  {id:122,name:"Egg Burji",cat:"Curries",subcat:"NonVeg",price:99,type:"nonveg",available:true,popular:false,tags:["curry","egg"],image:"assets/egg_dishes.png"},
  {id:123,name:"Boneless Chicken Curry",cat:"Curries",subcat:"NonVeg",price:179,type:"nonveg",available:true,popular:false,tags:["curry","chicken"],image:"assets/curry.png"},
  {id:124,name:"Kaju Boneless Chicken Curry",cat:"Curries",subcat:"NonVeg",price:199,type:"nonveg",available:true,popular:false,tags:["curry","chicken"],image:"assets/curry.png"},
  {id:125,name:"Butter Chicken Curry",cat:"Curries",subcat:"NonVeg",price:199,type:"nonveg",available:true,popular:true,tags:["curry","chicken","butter"],image:"assets/curry.png"},
  {id:126,name:"Chicken Tikka Masala",cat:"Curries",subcat:"NonVeg",price:119,type:"nonveg",available:true,popular:false,tags:["curry","chicken","tikka"],image:"assets/curry.png"},
  {id:127,name:"Chicken Shahi Kurma",cat:"Curries",subcat:"NonVeg",price:179,type:"nonveg",available:true,popular:false,tags:["curry","chicken"],image:"assets/curry.png"},
  {id:128,name:"Mughalai Chicken Curry",cat:"Curries",subcat:"NonVeg",price:199,type:"nonveg",available:true,popular:false,tags:["curry","chicken","mughlai"],image:"assets/curry.png"},
  {id:129,name:"Kadi Chicken Curry",cat:"Curries",subcat:"NonVeg",price:189,type:"nonveg",available:true,popular:false,tags:["curry","chicken"],image:"assets/curry.png"},
  {id:130,name:"Methi Chicken Curry",cat:"Curries",subcat:"NonVeg",price:199,type:"nonveg",available:true,popular:false,tags:["curry","chicken"],image:"assets/curry.png"},
  {id:131,name:"Prawns Curry",cat:"Curries",subcat:"NonVeg",price:249,type:"nonveg",available:true,popular:false,tags:["curry","prawns"],image:"assets/curry.png"},
  // Breads
  {id:132,name:"Tandoori Roti",cat:"Curries",subcat:"Breads",price:29,type:"veg",available:true,popular:false,tags:["bread"],image:"assets/paratha.png"},
  {id:133,name:"Garlic Naan",cat:"Curries",subcat:"Breads",price:45,type:"veg",available:true,popular:true,tags:["bread","garlic"],image:"assets/paratha.png"},
  {id:134,name:"Butter Naan",cat:"Curries",subcat:"Breads",price:39,type:"veg",available:true,popular:false,tags:["bread","butter"],image:"assets/paratha.png"},
  {id:135,name:"Pulka",cat:"Curries",subcat:"Breads",price:29,type:"veg",available:true,popular:false,tags:["bread"],image:"assets/paratha.png"},
  {id:136,name:"Aloo Parota",cat:"Curries",subcat:"Breads",price:59,type:"veg",available:true,popular:false,tags:["bread"],image:"assets/paratha.png"},
  {id:137,name:"Paneer Parota",cat:"Curries",subcat:"Breads",price:69,type:"veg",available:true,popular:false,tags:["bread","paneer"],image:"assets/paratha.png"},
  {id:138,name:"Meethi Parota",cat:"Curries",subcat:"Breads",price:59,type:"veg",available:true,popular:false,tags:["bread","sweet"],image:"assets/paratha.png"},
  {id:139,name:"Masala Kulcha",cat:"Curries",subcat:"Breads",price:59,type:"veg",available:true,popular:false,tags:["bread"],image:"assets/paratha.png"},
  {id:140,name:"Paneer Kulcha",cat:"Curries",subcat:"Breads",price:69,type:"veg",available:true,popular:false,tags:["bread","paneer"],image:"assets/paratha.png"},
  // Burgers
  {id:141,name:"Veg Burger",cat:"FastFood2",subcat:"Burgers",price:80,type:"veg",available:true,popular:false,tags:["burger","fast"],image:"assets/pizza_burger.png"},
  {id:142,name:"Veg Cheese Burger",cat:"FastFood2",subcat:"Burgers",price:100,type:"veg",available:true,popular:false,tags:["burger","fast","cheese"],image:"assets/pizza_burger.png"},
  {id:143,name:"Paneer Burger",cat:"FastFood2",subcat:"Burgers",price:100,type:"veg",available:true,popular:false,tags:["burger","fast","paneer"],image:"assets/pizza_burger.png"},
  {id:144,name:"Paneer Cheese Burger",cat:"FastFood2",subcat:"Burgers",price:119,type:"veg",available:true,popular:false,tags:["burger","fast","paneer","cheese"],image:"assets/pizza_burger.png"},
  {id:145,name:"Chicken Burger",cat:"FastFood2",subcat:"Burgers",price:110,type:"nonveg",available:true,popular:true,tags:["burger","fast","chicken"],image:"assets/pizza_burger.png"},
  {id:146,name:"Chicken Cheese Burger",cat:"FastFood2",subcat:"Burgers",price:130,type:"nonveg",available:true,popular:false,tags:["burger","fast","chicken","cheese"],image:"assets/pizza_burger.png"},
  // Pizza
  {id:147,name:"Veg Pizza (Small)",cat:"FastFood2",subcat:"Pizza",price:149,type:"veg",available:true,popular:false,tags:["pizza","fast"],image:"assets/pizza_burger.png"},
  {id:148,name:"Veg Pizza (Large)",cat:"FastFood2",subcat:"Pizza",price:189,type:"veg",available:true,popular:false,tags:["pizza","fast"],image:"assets/pizza_burger.png"},
  {id:149,name:"Paneer Pizza (Small)",cat:"FastFood2",subcat:"Pizza",price:169,type:"veg",available:true,popular:false,tags:["pizza","fast","paneer"],image:"assets/pizza_burger.png"},
  {id:150,name:"Paneer Pizza (Large)",cat:"FastFood2",subcat:"Pizza",price:219,type:"veg",available:true,popular:false,tags:["pizza","fast","paneer"],image:"assets/pizza_burger.png"},
  {id:151,name:"Chicken Cheese Pizza (Small)",cat:"FastFood2",subcat:"Pizza",price:209,type:"nonveg",available:true,popular:true,tags:["pizza","fast","chicken"],image:"assets/pizza_burger.png"},
  {id:152,name:"Chicken Cheese Pizza (Large)",cat:"FastFood2",subcat:"Pizza",price:279,type:"nonveg",available:true,popular:false,tags:["pizza","fast","chicken"],image:"assets/pizza_burger.png"},
  {id:153,name:"Chicken Double Cheese Pizza (Small)",cat:"FastFood2",subcat:"Pizza",price:229,type:"nonveg",available:true,popular:false,tags:["pizza","fast","chicken","cheese"],image:"assets/pizza_burger.png"},
  {id:154,name:"Chicken Double Cheese Pizza (Large)",cat:"FastFood2",subcat:"Pizza",price:299,type:"nonveg",available:true,popular:false,tags:["pizza","fast","chicken","cheese"],image:"assets/pizza_burger.png"},
  // Sandwiches
  {id:155,name:"Veg Sandwich",cat:"FastFood2",subcat:"Sandwich",price:80,type:"veg",available:true,popular:false,tags:["sandwich","fast"],image:"assets/pizza_burger.png"},
  {id:156,name:"Veg Cheese Sandwich",cat:"FastFood2",subcat:"Sandwich",price:100,type:"veg",available:true,popular:false,tags:["sandwich","fast","cheese"],image:"assets/pizza_burger.png"},
  {id:157,name:"Paneer Sandwich",cat:"FastFood2",subcat:"Sandwich",price:120,type:"veg",available:true,popular:false,tags:["sandwich","fast","paneer"],image:"assets/pizza_burger.png"},
  {id:158,name:"Veg Wrap",cat:"FastFood2",subcat:"Sandwich",price:99,type:"veg",available:true,popular:false,tags:["wrap","fast"],image:"assets/pizza_burger.png"},
  {id:159,name:"Paneer Wrap",cat:"FastFood2",subcat:"Sandwich",price:119,type:"veg",available:true,popular:false,tags:["wrap","fast","paneer"],image:"assets/pizza_burger.png"},
  {id:160,name:"Chicken Sandwich",cat:"FastFood2",subcat:"Sandwich",price:129,type:"nonveg",available:true,popular:false,tags:["sandwich","fast","chicken"],image:"assets/pizza_burger.png"},
  {id:161,name:"Chicken Cheese Sandwich",cat:"FastFood2",subcat:"Sandwich",price:139,type:"nonveg",available:true,popular:false,tags:["sandwich","fast","chicken","cheese"],image:"assets/pizza_burger.png"},
  {id:162,name:"Chicken Wrap",cat:"FastFood2",subcat:"Sandwich",price:129,type:"nonveg",available:true,popular:false,tags:["wrap","fast","chicken"],image:"assets/pizza_burger.png"},
  {id:163,name:"Bread Omelette",cat:"FastFood2",subcat:"Sandwich",price:99,type:"nonveg",available:true,popular:false,tags:["bread","egg"],image:"assets/egg_dishes.png"},
  // Beverages
  {id:164,name:"Mocktail (Virgin Mojito)",cat:"Beverages",subcat:"Mocktails",price:79,type:"veg",available:true,popular:true,tags:["drink","mocktail"],image:"assets/drinks.png"},
  {id:165,name:"Mocktail (Strawberry)",cat:"Beverages",subcat:"Mocktails",price:79,type:"veg",available:true,popular:false,tags:["drink","mocktail"],image:"assets/drinks.png"},
  {id:166,name:"Mocktail (Watermelon)",cat:"Beverages",subcat:"Mocktails",price:79,type:"veg",available:true,popular:false,tags:["drink","mocktail"],image:"assets/drinks.png"},
  {id:167,name:"Apple Juice",cat:"Beverages",subcat:"Juices",price:80,type:"veg",available:true,popular:false,tags:["drink","juice"],image:"assets/drinks.png"},
  {id:168,name:"Orange Juice",cat:"Beverages",subcat:"Juices",price:70,type:"veg",available:true,popular:false,tags:["drink","juice"],image:"assets/drinks.png"},
  {id:169,name:"Watermelon Juice",cat:"Beverages",subcat:"Juices",price:50,type:"veg",available:true,popular:false,tags:["drink","juice"],image:"assets/drinks.png"},
  {id:170,name:"Belgium Chocolate Shake",cat:"Beverages",subcat:"Shakes",price:120,type:"veg",available:true,popular:true,tags:["drink","shake","chocolate"],image:"assets/shakes.png"},
  {id:171,name:"Oreo Shake",cat:"Beverages",subcat:"Shakes",price:120,type:"veg",available:true,popular:false,tags:["drink","shake"],image:"assets/shakes.png"},
  {id:172,name:"Cold Coffee",cat:"Beverages",subcat:"Shakes",price:120,type:"veg",available:true,popular:true,tags:["drink","coffee"],image:"assets/shakes.png"},
];

// Dynamically assign images to each item according to its name
MENU_DATA.forEach(item => {
    // Generate a placeholder image with the item's name on it
    const text = encodeURIComponent(item.name);
    // Dark background matching the theme, with accent-colored text
    item.image = `https://placehold.co/400x300/2a2a35/ff6b35?text=${text}`;
});
